export enum FireEmblem {
  Heroes = 'Fire Emblem Heroes',
  ShadowDragon = 'Fire Emblem: Shadow Dragon and the Blade of Light',
  MysteryEmblem = 'Fire Emblem: Mystery of the Emblem',
  NewMysteryEmblem = 'Fire Emblem: New Mystery of the Emblem',
  ShadowsOfValentia = 'Fire Emblem Echoes: Shadows of Valentia',
  GeneologyOfTheHolyWar = 'Fire Emblem: Genealogy of the Holy War',
  Thracia776 = 'Fire Emblem: Thracia 776',
  BindingBlade = 'Fire Emblem: The Binding Blade',
  BlazingBlade = 'Fire Emblem: The Blazing Blade',
  SacredStones = 'Fire Emblem: The Sacred Stones',
  PathOfRadiance = 'Fire Emblem: Path of Radiance',
  RadiantDawn = 'Fire Emblem: Radiant Dawn',
  Awakening = 'Fire Emblem Awakening',
  Fates = 'Fire Emblem Fates',
  ThreeHopes = 'Fire Emblem Warriors: Three Hopes',
  ThreeHouses = 'Fire Emblem: Three Houses',
  TokyoMirageSessions = 'Tokyo Mirage Sessions ♯FE Encore',
  Engage = 'Fire Emblem Engage',
}
