export enum SkillName {
  Atk = 'Atk',
  ARDDefRes = 'AR-D Def/Res',
  ARDAtkDef = 'AR-D Atk/Def',
  DeathBlow = 'Death Blow',
  FierceStance = 'Fierce Stance',
  Spd = 'Spd',
  HP = 'HP',
  Def = 'Def',
  Res = 'Res',
  HPAtk = 'HP/Atk',
  HPSpd = 'HP/Spd',
  HPDef = 'HP/Def',
  HPRes = 'HP/Res',
  AtkSpd = 'Atk/Spd',
  AtkDef = 'Atk/Def',
  AtkRes = 'Atk/Res',
  SpdDef = 'Spd/Def',
  SpdRes = 'Spd/Res',
  DefRes = 'Def/Res',
  FortressDef = 'Fortress Def',
  FortressRes = 'Fortress Res',
  FortressDefRes = 'Fortress Def/Res',
  SvalinnShield = 'Svalinn Shield',
  GranisShield = "Grani's Shield",
  IotesShield = "Iote's Shield",
}

export enum SkillDescription {
  GrantsStat = 'Grants stats to unit',
  GrantsInCombatStat = 'Grants unit stats in combat',
  GrantsInCombatStatByStructure = 'Grants unit stats in combat by AR structure',
  NeutralizeArmorEffectiveness = 'Neutralizes "effective against armored" bonuses',
  NeutralizeCavalryEffectiveness = 'Neutralizes "effective against cavalry" bonuses',
  NeutralizeFlierEffectiveness = 'Neutralizes "effective against fliers" bonuses',
}
